version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: brigzzy/submitspell:latest
    deploy:
      replicas: 20
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
